package com.aksar.dungru.utils

object Constance {
    const val WebClientId = "649190876143-6c2ka2povis2q0pssid9np5ucv8vmitd.apps.googleusercontent.com"
    const val ImageBaseUrl = "https://dungru.aksarinfoedge.com/public/uploads/images/"
    const val GOOGLE = "Google"
    const val FACEBOOK = "Facebook"
    const val Flow = "Flow"
    const val USER_ID = "USER_ID"
    const val SignIn = "SignIn"
    const val SignUp = "SignUp"
    const val Otp = "Otp"
    const val ForgotPassword = "ForgotPassword"
    const val VIDEO = "Video"
    const val IMAGE = "Image"
    const val ALL = "All"
    const val SetPassword = "SetPassword"
    const val Live = "Live"
    const val SearchResults = "SearchResults"
    const val SearchFilter = "SearchFilter"
    const val Amount = "amount"
    const val GeneralSetting = "GeneralSetting"
    const val DataPass = "Data"
    const val Notification = "Notification"
    const val Follower = "Follower"
    const val Following = "Following"
    const val HelpCenter = "HelpCenter"
    const val Feedback = "Feedback"
    const val Transaction_History_Add = "TransactionHistoryAdd"
    const val Transaction_History_Withdraw = "TransactionHistoryWithdraw"
    const val Wallet_History = "WalletHistory"
}